package com.kalandyk.exception;

/**
 * Created by kamil on 3/20/14.
 */
public enum ExceptionType {

    CUSTOM,
    DEBT_CREATION_EXCEPTION,
    CONFIRMATION_CREATION_EXCEPTION,
    USER_CREATION_EXCEPTION,
    USER_EDITING_EXCEPTION,
    AUTHENTICATION_ERROR,
    DEBT_EDITION_EXCEPTION,
    PERMISSION_DENIED

}
