package com.kalandyk.api.model;

/**
 * Created by kamil on 12/29/13.
 */
public enum DebtEventType {

    DEBT_SIMPLE_ADDITION,
    DEBT_SIMPLE_REPAYMENT,



    DEBT_ADDITION_REQUEST,
    DEBT_ADDITION_APPROVING,
    DEBT_ADDITION_REJECTING,

    DEBT_REQUEST_REPAY,
    DEBT_CANCELING_REPAYMENT_REQUEST,
    DEBT_REJECTING_REPAYMENT_REQUEST,
    DEBT_APPROVING_REPAYMENT_REQUEST,


}
